FROM node:18-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./backend/
COPY backend/.npmrc ./backend/
RUN cd backend && npm install

COPY backend/ ./backend/

WORKDIR /app/backend
CMD ["npx", "nodemon", "src/server.js", "--ext", "js", "--exec", "babel-node"]
