FROM node:18-alpine

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./backend/
RUN cd backend && npm install

COPY backend/ ./backend/

CMD ["npx", "--prefix", "backend", "nodemon", "src/server.js", "--ext", "js", "--exec", "babel-node"]
